### ISSUE TITLE
Header with null value if not present on query context

### ISSUE THREAD

**Issue by MachadoLhes** [B2W-BIT/restQL-http#106]
How should restQL behave when a param is not present in context?

Today, if a param is set in query but isn't present in the query context, it is interpreted as *null*, the problem is that this behavior causes an error if the param is a header. Headers can't be *null*, but they can indeed be an empty string.

We can't just simply substitute _nil_ for _" "_, because it would interfere if a parameter is null on purpose.

**Comment by lucasbarros** [comment]
restQL should skip the request with a inexistent variable.

https://github.com/B2W-BIT/restQL-clojure/blob/205ee9443d8d741d4c819633c418494400d145b6/src/main/restql/core/runner/request.clj#L278-L286

For a conditional variable we should implement the issue #84
