### ISSUE TITLE
non-existing env.sh

### ISSUE THREAD

**Issue by wzhliang** [B2W-BIT/restQL-http#140]
I'm trying to follow the tutorial but the mentioned file isn't in the release zip

       3. Edit the file env.sh with the resources you want to invoke,

**Comment by lucasbarros** [comment]
Hi @wzhliang, 

this part of docs was out of date, sorry. I just updated.
You do not need to use `env.sh` anymore, only thing you need is to set your resource mappings ([full documentation link](http://docs.restql.b2w.io/#/restql/resource-mappings)) and run the restQL server.

```sh
$ export RESOURCE_NAME=http://resource-url
$ ./bin/run.sh
```

**Comment by wzhliang** [comment]
thanks
