### ISSUE TITLE
Proper encoding of URL parameters

### ISSUE THREAD

**Issue by fschaefer** [B2W-BIT/restQL-http#173]
Some services use an array syntax for query parameters like `http://example.com?abc[]=123&abc[]=456`

I tried to query such a service with something like:
```
from tenants as tenant
    with
        tenantDomain = "123456.sms"
        props[] = "tenantDomain"
```
without success. Quoting or encoding the parameters also dosn't work and results in a `PARSE_ERROR`.

How to proper quote such kind of parameters?

**Comment by ricardoekm** [comment]
@lucasbarros and @cupello is this just a matter of updating the grammar (BNF)?
