### ISSUE TITLE
Implement mutations (i.e. POST, PUT and DELETE)

### ISSUE THREAD

**Issue by ricardoekm** [B2W-BIT/restQL-http#20]
Currently restQL only works with HTTP GET method.

Implement POST, PUT and DELETE would allow reduced network roundtrip for scenarios where resource query and creation take place on the same screen, e.g. get product and create cart.

Also some query APIs, due to payload limitation, exposes their requests via POST.

The proposal is to add three new keywords:
- to (POST),
- into (PUT),
- delete (DELETE)

e.g.:
```
to customer 
with name = "Ricardo Mayerhofer"
```

### Body

We have to figure out how to encode the body in POST and PUT requests. The initial proposal is to always use JSON.

### URL params

URL params should have precendence over body params. This means if the resource has a declared URL param (e.g. /customer/${id}) if the user declare this parameter in the query it should be used as URL parameter instead of a body parameter.

### Query string params

We should allow the user state in the resource definition the query-parameters of the resource. This'll have the same effect of URL params precedence. Query string params will have precedence over body params.

**Comment by sio-iago** [comment]
This was added in restQL core. @ricardoekm can you please generate a new version and close this issue?

**Comment by lucasbarros** [comment]
This feature was added on release [v2.6.2](https://github.com/B2W-BIT/restQL-http/releases/tag/v2.6.2)
