### ISSUE TITLE
Filter items in an array based on criteria

### ISSUE THREAD

**Issue by ricardoekm** [B2W-BIT/restQL-http#21]
restQL should allow the user to filter items in a multiplexed requests or in resources that returns an array.

This should include nested arrays. This would allow reduced payload in such scenarios.

Example:

```json
[
   { "type": "SPECIAL", "name": "Batman" },
   { "type": "REGULAR", "name": "Robin" }
]
```
Filter items with type regular.

**Comment by lucasbarros** [comment]
I think that this is a good case to use Input Function (#67)
