### ISSUE TITLE
restQL-core-js

### ISSUE THREAD

**Issue by ricardoekm** [B2W-BIT/restQL-http#25]
We should compile restQL-core in ClojureScript/Javascript. This allows the user to embed restQL directly into a Javascript project.

Furthermore, this is a step toward rewriting some parts in Javascript and embrace javascript community.

**Comment by cupello** [comment]
restQL-core compiles to NodeJs now!!!! https://github.com/B2W-BIT/restQL-clojure/pull/75

**Comment by lucasbarros** [comment]
restQL js was deployed to NPM in https://www.npmjs.com/package/@b2wdigital/restql
