### ISSUE TITLE
Concatenate string with variables

### ISSUE THREAD

**Issue by ricardoekm** [B2W-BIT/restQL-http#27]
it will be interesting if we could concatenate strings with variables from the query-string or from another resource like:

from resource:
    with:
       parameter = `stringvalue:${variable}`

Moved from: https://github.com/B2W-BIT/restQL-core/issues/11

**Comment by jsanchesleao** [comment]
I didn't get it. Shouldn't it be something like this?

```
from resource
with
  parameter = "stringvalue${variable}"
```

So it would not conflict with the chaining syntax

**Comment by cupello** [comment]
This should be solved with functions #47 .
