### ISSUE TITLE
restQL should skip a resource call if a parameter is not present

### ISSUE THREAD

**Issue by ricardoekm** [B2W-BIT/restQL-http#36]
The return should be 400 with a message indicating that the resource was skipped.

**Comment by MachadoLhes** [comment]
What if a parameter is optional?
Maybe we should make it so that only some annotated params are required and skip the resource only if a required parameter isn't present.
Optional params (the ones which are not annotated) will mantain the current behavior.

**Comment by lucasbarros** [comment]
We need to differentiate between null and non-existent parameters
