### ISSUE TITLE
New functions support

### ISSUE THREAD

**Issue by ricardoekm** [B2W-BIT/restQL-http#47]
restQL should make it easy to develop, use and compose functions.

We should have two functions categories

## Params functions
Params functions are functions acting on param inputs (inside _with_ clause). 

Examples of this type of functions are format converters: json, base64 (previously called encoders) and flatten function. If a param function returns an array the request should be multiplexed. 

## Response functions
Response functions are functions acting on query response. 

Examples of this type of functions are filters: matches function and general response transformers.

**Comment by lucasbarros** [comment]
Move to #67
