### ISSUE TITLE
restQL crashes with inexistent queries 

### ISSUE THREAD

**Issue by lucasbarros** [B2W-BIT/restQL-http#58]
When I get an query that was not saved yet, restQL http returns a `PARSE_ERROR` response and caches it forever.

I think that the ideal beheivor in this case is to return 404 response and doesn't cache the query.

Any suggestion?

Ex:
- GET `run-query/namespace/test-query/1`
- STATUS `400`
```json
{
    "message": {
        "error": "PARSE_ERROR",
        "line":2,
        "column":1
    }
}
```

**Comment by ricardoekm** [comment]
I agree it should return a 404.
